const QRCode = require('qrcode');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const QRCodeModel = require('../models/QRCode');
const MerchantModel = require('../models/Merchant');
const User = require('../models/User');

class QRCodeService {
  constructor() {
    this.uploadDir = path.join(__dirname, '../../public/uploads/qrcodes');
    this.ensureUploadDirExists();
  }

  /**
   * Ensure upload directory exists
   */
  ensureUploadDirExists() {
    if (!fs.existsSync(this.uploadDir)) {
      fs.mkdirSync(this.uploadDir, { recursive: true });
    }
  }

  /**
   * Generate a unique filename for QR code
   * @param {number} merchantId - Merchant ID
   * @returns {string} Unique filename
   */
  generateUniqueFilename(merchantId) {
    const timestamp = Date.now();
    const randomString = crypto.randomBytes(8).toString('hex');
    return `qrcode_merchant_${merchantId}_${timestamp}_${randomString}.png`;
  }

  /**
   * Generate QR code data
   * @param {number} merchantId - Merchant ID
   * @returns {string} QR code data
   */
  generateQRCodeData(merchantId) {
    // Create a unique token for this QR code
    const uniqueToken = crypto.randomBytes(32).toString('hex');
    
    // Data to encode in QR code
    // This could be a URL to your WiFi connection page with the token
    const baseUrl = process.env.FRONTEND_URL || 'https://wifi-platform.com';
    const qrData = `${baseUrl}/connect?merchant=${merchantId}&token=${uniqueToken}`;
    
    return qrData;
  }

  /**
   * Generate and save QR code for a merchant
   * @param {number} merchantId - Merchant ID
   * @param {number} agentId - Agent user ID
   * @returns {Promise<Object>} Created QR code data
   */
  async generateQRCode(merchantId, agentId) {
    try {
      // Check if merchant exists
      const merchant = await MerchantModel.findById(merchantId);
      if (!merchant) {
        throw new Error('Merchant not found');
      }

      // Check if agent exists
      const agent = await User.findById(agentId);
      if (!agent || agent.role !== 'agent') {
        throw new Error('Agent not found or invalid');
      }

      // Generate QR code data
      const qrData = this.generateQRCodeData(merchantId);
      
      // Generate unique filename
      const filename = this.generateUniqueFilename(merchantId);
      const filePath = path.join(this.uploadDir, filename);
      
      // Generate QR code image
      await QRCode.toFile(filePath, qrData, {
        errorCorrectionLevel: 'H',
        margin: 1,
        width: 300,
        color: {
          dark: '#000000',
          light: '#ffffff'
        }
      });
      
      // Calculate relative URL for storage in database
      const relativeUrl = `/uploads/qrcodes/${filename}`;
      
      // Deactivate existing QR codes for this merchant
      await this.deactivateExistingQRCodes(merchantId);
      
      // Create QR code record in database
      const qrCode = await QRCodeModel.create({
        merchant_id: merchantId,
        code_image_url: relativeUrl,
        activation_status: 'ACTIVE',
        created_by: agentId
      });
      
      return qrCode;
    } catch (error) {
      console.error('QR code generation error:', error);
      throw error;
    }
  }

  /**
   * Deactivate existing QR codes for a merchant
   * @param {number} merchantId - Merchant ID
   * @returns {Promise<boolean>} Success status
   */
  async deactivateExistingQRCodes(merchantId) {
    try {
      const activeQRCodes = await QRCodeModel.findByMerchantId(merchantId);
      
      for (const qrCode of activeQRCodes) {
        if (qrCode.activation_status === 'ACTIVE') {
          await QRCodeModel.updateStatus(qrCode.id, 'inactive');
        }
      }
      
      return true;
    } catch (error) {
      console.error('Error deactivating QR codes:', error);
      throw error;
    }
  }

  /**
   * Get active QR code for a merchant
   * @param {number} merchantId - Merchant ID
   * @returns {Promise<Object|null>} QR code data or null
   */
  async getActiveQRCode(merchantId) {
    try {
      return await QRCodeModel.findActiveMerchantQRCode(merchantId);
    } catch (error) {
      console.error('Error fetching active QR code:', error);
      throw error;
    }
  }

  /**
   * Get all QR codes for a merchant
   * @param {number} merchantId - Merchant ID
   * @returns {Promise<Array>} Array of QR codes
   */
  async getMerchantQRCodes(merchantId) {
    try {
      return await QRCodeModel.findByMerchantId(merchantId);
    } catch (error) {
      console.error('Error fetching merchant QR codes:', error);
      throw error;
    }
  }

  /**
   * Get all QR codes generated by an agent
   * @param {number} agentId - Agent user ID
   * @returns {Promise<Array>} Array of QR codes with merchant data
   */
  async getAgentQRCodes(agentId) {
    try {
      return await QRCodeModel.findByAgentId(agentId);
    } catch (error) {
      console.error('Error fetching agent QR codes:', error);
      throw error;
    }
  }

  /**
   * Activate or deactivate a QR code
   * @param {number} qrCodeId - QR code ID
   * @param {string} status - New status ('ACTIVE' or 'inactive')
   * @returns {Promise<Object>} Updated QR code
   */
  async updateQRCodeStatus(qrCodeId, status) {
    try {
      if (status !== 'ACTIVE' && status !== 'inactive') {
        throw new Error('Invalid status. Use "active" or "inactive"');
      }
      
      const qrCode = await QRCodeModel.findById(qrCodeId);
      if (!qrCode) {
        throw new Error('QR code not found');
      }
      
      // If activating, deactivate other QR codes for the same merchant
      if (status === 'ACTIVE') {
        await this.deactivateExistingQRCodes(qrCode.merchant_id);
      }
      
      // Update status
      return await QRCodeModel.updateStatus(qrCodeId, status);
    } catch (error) {
      console.error('Error updating QR code status:', error);
      throw error;
    }
  }

  /**
   * Validate QR code token from scan
   * @param {number} merchantId - Merchant ID from QR code
   * @param {string} token - Token from QR code
   * @returns {Promise<Object>} Validation result with merchant data
   */
  async validateQRCodeToken(merchantId, token) {
    try {
      // In a real implementation, you would store and verify tokens
      // For now, we'll just check if the merchant exists and has an active QR code
      const merchant = await MerchantModel.findById(merchantId);
      if (!merchant) {
        throw new Error('Invalid QR code: Merchant not found');
      }
      
      const activeQRCode = await QRCodeModel.findActiveMerchantQRCode(merchantId);
      if (!activeQRCode) {
        throw new Error('Invalid QR code: No active QR code found');
      }
      
      // Get WiFi settings
      const merchantWithWiFiSettings = await MerchantModel.findWithWiFiSettings(merchantId);
      
      return {
        isValid: true,
        merchant: merchantWithWiFiSettings,
        qrCode: activeQRCode
      };
    } catch (error) {
      console.error('QR code validation error:', error);
      return {
        isValid: false,
        error: error.message
      };
    }
  }

  /**
   * Delete a QR code
   * @param {number} qrCodeId - QR code ID
   * @returns {Promise<boolean>} Success status
   */
  async deleteQRCode(qrCodeId) {
    try {
      const qrCode = await QRCodeModel.findById(qrCodeId);
      if (!qrCode) {
        throw new Error('QR code not found');
      }
      
      // Delete the image file if it exists
      if (qrCode.code_image_url) {
        const filePath = path.join(__dirname, '../../public', qrCode.code_image_url);
        if (fs.existsSync(filePath)) {
          fs.unlinkSync(filePath);
        }
      }
      
      // Delete from database
      await QRCodeModel.delete(qrCodeId);
      
      return true;
    } catch (error) {
      console.error('Error deleting QR code:', error);
      throw error;
    }
  }
}

module.exports = new QRCodeService();